import { prisma } from "@/lib/prisma";
import { PropertyType, Status } from "../generated/prisma/enums";

async function main() {
  const properties = [
    {
      title: "Modern Apartment in Yangon Downtown",
      description:
        "A spacious and modern apartment located in the heart of downtown Yangon. This unit offers convenient access to Sule Pagoda, shopping malls, restaurants, and public transportation. The apartment is well-ventilated with natural light, fully furnished with air conditioning, washing machine, refrigerator, and high-speed internet. Ideal for young professionals or small families looking for comfort and accessibility.",
      baseRentPrice: 450000,
      beds: 2,
      baths: 1,
      area: 850,
      propertyType: "Apartment",
      locationAddress: "Kyauktada Township, Yangon",
      coordinates: [16.774, 96.158],
      images: ["apartment1.jpg", "apartment2.jpg", "apartment3.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.3,
      parkingSpaces: 1,
      yearBuilt: 2018,
      petAllowed: false,
      appliances: ["AC", "Fridge", "Washing Machine"],
      availableDate: "2026-04-01T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "100 Mbps",
    },
    {
      title: "Luxury Condo with Pool in Yankin",
      description:
        "High-end condominium in Yankin Township featuring a swimming pool, gym, 24/7 security, and backup generator. The unit comes fully furnished with modern interior design, large balcony, and city views. Close to Myanmar Plaza, international schools, and business centers. Perfect for expatriates and executives.",
      baseRentPrice: 1200000,
      beds: 3,
      baths: 2,
      area: 1200,
      propertyType: "Condo",
      locationAddress: "Yankin Township, Yangon",
      coordinates: [16.816, 96.164],
      images: ["condo1.jpg", "condo2.jpg", "condo3.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.5,
      parkingSpaces: 2,
      yearBuilt: 2020,
      petAllowed: true,
      appliances: ["AC", "TV", "Microwave"],
      availableDate: "2026-04-10T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MPT Fiber",
      internetSpeed: "500 Mbps",
    },
    {
      title: "Family House in North Dagon",
      description:
        "A peaceful standalone house located in North Dagon, suitable for large families. The property includes a private garden, multiple bedrooms, and spacious living areas. Nearby schools, markets, and clinics make it convenient for daily living. Quiet neighborhood with friendly community.",
      baseRentPrice: 600000,
      beds: 4,
      baths: 2,
      area: 2000,
      propertyType: "House",
      locationAddress: "North Dagon Township, Yangon",
      coordinates: [16.903, 96.195],
      images: ["house1.jpg", "house2.jpg", "house3.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.8,
      parkingSpaces: 2,
      yearBuilt: 2015,
      petAllowed: true,
      appliances: ["Fan", "Water Heater"],
      availableDate: "2026-05-01T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "Ooredoo Fiber",
      internetSpeed: "80 Mbps",
    },
    {
      title: "Premium Villa in Inya Lake Area",
      description:
        "Exclusive villa located near Inya Lake offering a luxurious lifestyle with private garden, large compound, and premium interiors. This property includes modern kitchen, spacious bedrooms, and a serene environment. Ideal for diplomats or high-income tenants seeking privacy and comfort.",
      baseRentPrice: 2500000,
      beds: 5,
      baths: 4,
      area: 3500,
      propertyType: "Villa",
      locationAddress: "Kamayut Township, Yangon",
      coordinates: [16.83, 96.135],
      images: ["villa1.jpg", "villa2.jpg", "villa3.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 1.2,
      parkingSpaces: 3,
      yearBuilt: 2019,
      petAllowed: true,
      appliances: ["AC", "Oven", "Dishwasher"],
      availableDate: "2026-04-15T00:00:00.000Z",
      leaseTermMonths: 24,
      internetName: "MyTel Fiber",
      internetSpeed: "1 Gbps",
    },
    {
      title: "Affordable Apartment in Hlaing",
      description:
        "A well-maintained and budget-friendly apartment located in the vibrant Hlaing Township, popular among students and IT professionals. It offers excellent access to universities, tech hubs, markets, and public transportation. The unit features good ventilation, natural lighting, and a practical layout, making it ideal for individuals or couples seeking affordability with convenience.",
      baseRentPrice: 300000,
      beds: 1,
      baths: 1,
      area: 600,
      propertyType: "Apartment",
      status: "AVAILABLE",
      locationAddress: "Hlaing Township, Yangon",
      coordinates: [16.84, 96.13],
      images: ["apartment4.jpg", "apartment5.jpg", "apartment6.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.4,
      parkingSpaces: 1,
      yearBuilt: 2016,
      petAllowed: false,
      appliances: ["Fan", "AC"],
      availableDate: "2026-04-05T00:00:00.000Z",
      leaseTermMonths: 6,
      internetName: "MPT Fiber",
      internetSpeed: "50 Mbps",
    },
    {
      title: "City Condo in Sanchaung",
      description:
        "This modern condominium unit in Sanchaung Township offers a dynamic urban lifestyle surrounded by cafes, restaurants, and shopping centers. The property features a contemporary interior, functional layout, and comfortable living space, making it ideal for professionals and small families.",
      baseRentPrice: 900000,
      beds: 2,
      baths: 2,
      area: 1000,
      propertyType: "Condo",
      status: "AVAILABLE",
      locationAddress: "Sanchaung Township, Yangon",
      coordinates: [16.799, 96.129],
      images: ["condo4.jpg", "condo5.jpg", "condo6.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.6,
      parkingSpaces: 1,
      yearBuilt: 2021,
      petAllowed: true,
      appliances: ["AC", "TV", "Washing Machine"],
      availableDate: "2026-04-08T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "300 Mbps",
    },
    {
      title: "Cozy House in Thingangyun",
      description:
        "A charming standalone house located in a peaceful residential area of Thingangyun Township. The property offers spacious living areas, multiple bedrooms, and a comfortable environment suitable for families.",
      baseRentPrice: 500000,
      beds: 3,
      baths: 2,
      area: 1500,
      propertyType: "House",
      status: "AVAILABLE",
      locationAddress: "Thingangyun Township, Yangon",
      coordinates: [16.827, 96.193],
      images: ["house4.jpg", "house5.jpg", "house6.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.7,
      parkingSpaces: 2,
      yearBuilt: 2014,
      petAllowed: true,
      appliances: ["Fan", "Water Heater"],
      availableDate: "2026-04-12T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "Ooredoo",
      internetSpeed: "60 Mbps",
    },
    {
      title: "Luxury Villa in Bahan",
      description:
        "An elegant villa located in the prestigious Bahan Township near Shwedagon Pagoda. This property offers premium interiors, spacious rooms, and a peaceful environment suitable for luxury living.",
      baseRentPrice: 3000000,
      beds: 5,
      baths: 4,
      area: 3800,
      propertyType: "Villa",
      status: "AVAILABLE",
      locationAddress: "Bahan Township, Yangon",
      coordinates: [16.805, 96.149],
      images: ["villa4.jpg", "villa5.jpg", "villa6.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 1.0,
      parkingSpaces: 3,
      yearBuilt: 2020,
      petAllowed: true,
      appliances: ["AC", "Oven", "Dishwasher"],
      availableDate: "2026-04-15T00:00:00.000Z",
      leaseTermMonths: 24,
      internetName: "MyTel Fiber",
      internetSpeed: "1 Gbps",
    },
    {
      title: "Apartment near Mandalay Palace",
      description:
        "A well-located apartment in Mandalay offering peaceful surroundings near the historic Mandalay Palace. The property provides good ventilation and easy access to local markets and transport.",
      baseRentPrice: 350000,
      beds: 2,
      baths: 1,
      area: 800,
      propertyType: "Apartment",
      status: "AVAILABLE",
      locationAddress: "Chanayethazan, Mandalay",
      coordinates: [21.984, 96.084],
      images: ["apartment7.jpg", "apartment8.jpg", "apartment9.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.9,
      parkingSpaces: 1,
      yearBuilt: 2017,
      petAllowed: false,
      appliances: ["Fan", "AC"],
      availableDate: "2026-04-20T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MPT Fiber",
      internetSpeed: "80 Mbps",
    },
    {
      title: "Condo in Naypyidaw Zabuthiri",
      description:
        "A modern condo in Zabuthiri Township offering a peaceful and organized environment with convenient access to government offices and shopping areas.",
      baseRentPrice: 700000,
      beds: 2,
      baths: 2,
      area: 950,
      propertyType: "Condo",
      status: "AVAILABLE",
      locationAddress: "Zabuthiri, Naypyidaw",
      coordinates: [19.763, 96.078],
      images: ["condo7.jpg", "condo8.jpg", "condo9.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 1.5,
      parkingSpaces: 1,
      yearBuilt: 2019,
      petAllowed: false,
      appliances: ["AC", "TV"],
      availableDate: "2026-04-18T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "100 Mbps",
    },
    {
      title: "House in Taunggyi Hills",
      description:
        "A scenic house located in the cool hills of Taunggyi with breathtaking mountain views and a refreshing climate year-round.",
      baseRentPrice: 450000,
      beds: 3,
      baths: 2,
      area: 1800,
      propertyType: "House",
      status: "AVAILABLE",
      locationAddress: "Taunggyi, Shan State",
      coordinates: [20.789, 97.037],
      images: ["house7.jpg", "house8.jpg", "house9.jpg"],
      nearTransitType: "Taxi Stand",
      nearTransitDist: 2.0,
      parkingSpaces: 2,
      yearBuilt: 2013,
      petAllowed: true,
      appliances: ["Fireplace", "Water Heater"],
      availableDate: "2026-04-25T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MPT Fiber",
      internetSpeed: "50 Mbps",
    },
    {
      title: "Beach Villa in Ngapali",
      description:
        "A luxurious beachfront villa offering direct sea access and stunning ocean views, ideal for premium coastal living.",
      baseRentPrice: 3500000,
      beds: 4,
      baths: 3,
      area: 3000,
      propertyType: "Villa",
      status: "AVAILABLE",
      locationAddress: "Ngapali Beach, Rakhine",
      coordinates: [18.45, 94.36],
      images: ["villa7.jpg", "villa8.jpg", "villa9.jpg"],
      nearTransitType: "Taxi Stand",
      nearTransitDist: 3.5,
      parkingSpaces: 2,
      yearBuilt: 2021,
      petAllowed: true,
      appliances: ["AC", "Pool", "Outdoor Kitchen"],
      availableDate: "2026-05-01T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "200 Mbps",
    },
    {
      title: "Apartment in South Okkalapa",
      description:
        "A practical apartment located near markets, schools, and transport routes, suitable for small families.",
      baseRentPrice: 320000,
      beds: 2,
      baths: 1,
      area: 700,
      propertyType: "Apartment",
      status: "AVAILABLE",
      locationAddress: "South Okkalapa, Yangon",
      coordinates: [16.85, 96.2],
      images: ["apartment10.jpg", "apartment11.jpg", "apartment12.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.4,
      parkingSpaces: 1,
      yearBuilt: 2015,
      petAllowed: false,
      appliances: ["Fan"],
      availableDate: "2026-04-22T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "Ooredoo Fiber",
      internetSpeed: "60 Mbps",
    },
    {
      title: "Condo in Dagon Seikkan",
      description:
        "A newly developed condo in a growing township with improving infrastructure and modern living conditions.",
      baseRentPrice: 650000,
      beds: 2,
      baths: 2,
      area: 900,
      propertyType: "Condo",
      status: "AVAILABLE",
      locationAddress: "Dagon Seikkan, Yangon",
      coordinates: [16.88, 96.24],
      images: ["condo10.jpg", "condo11.jpg", "condo12.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.9,
      parkingSpaces: 1,
      yearBuilt: 2022,
      petAllowed: true,
      appliances: ["AC", "TV"],
      availableDate: "2026-04-28T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "150 Mbps",
    },
    {
      title: "House in Insein",
      description:
        "A spacious and affordable house suitable for large families, located near essential facilities.",
      baseRentPrice: 550000,
      beds: 4,
      baths: 2,
      area: 2000,
      propertyType: "House",
      status: "AVAILABLE",
      locationAddress: "Insein, Yangon",
      coordinates: [16.91, 96.1],
      images: ["house10.jpg", "house11.jpg", "house12.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 1.1,
      parkingSpaces: 2,
      yearBuilt: 2012,
      petAllowed: true,
      appliances: ["Fan", "Water Heater"],
      availableDate: "2026-05-02T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MPT Fiber",
      internetSpeed: "80 Mbps",
    },
    {
      title: "Villa in Pyin Oo Lwin",
      description:
        "A charming villa surrounded by greenery and colonial architecture, offering a peaceful lifestyle.",
      baseRentPrice: 1800000,
      beds: 4,
      baths: 3,
      area: 2800,
      propertyType: "Villa",
      status: "AVAILABLE",
      locationAddress: "Pyin Oo Lwin",
      coordinates: [22.03, 96.47],
      images: ["villa10.jpg", "villa11.jpg", "villa12.jpg"],
      nearTransitType: "Taxi Stand",
      nearTransitDist: 1.8,
      parkingSpaces: 2,
      yearBuilt: 2018,
      petAllowed: true,
      appliances: ["Fireplace", "AC"],
      availableDate: "2026-05-05T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "100 Mbps",
    },
    {
      title: "Apartment in Tamwe",
      description:
        "A well-located apartment offering easy access to downtown Yangon and nearby commercial areas.",
      baseRentPrice: 400000,
      beds: 2,
      baths: 1,
      area: 750,
      propertyType: "Apartment",
      status: "AVAILABLE",
      locationAddress: "Tamwe, Yangon",
      coordinates: [16.8, 96.17],
      images: ["apartment13.jpg", "apartment14.jpg", "apartment15.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.5,
      parkingSpaces: 1,
      yearBuilt: 2016,
      petAllowed: false,
      appliances: ["Fan", "AC"],
      availableDate: "2026-04-26T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "Ooredoo Fiber",
      internetSpeed: "70 Mbps",
    },
    {
      title: "Condo in Hlaing Tharyar",
      description:
        "A functional condo near industrial zones, ideal for professionals working nearby.",
      baseRentPrice: 500000,
      beds: 2,
      baths: 1,
      area: 850,
      propertyType: "Condo",
      status: "AVAILABLE",
      locationAddress: "Hlaing Tharyar, Yangon",
      coordinates: [16.85, 95.95],
      images: ["condo13.jpg", "condo14.jpg", "condo15.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 1.3,
      parkingSpaces: 1,
      yearBuilt: 2020,
      petAllowed: false,
      appliances: ["AC"],
      availableDate: "2026-04-30T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MPT Fiber",
      internetSpeed: "100 Mbps",
    },
    {
      title: "House in Shwepyitha",
      description:
        "An affordable house in a developing township with growing infrastructure.",
      baseRentPrice: 450000,
      beds: 3,
      baths: 2,
      area: 1700,
      propertyType: "House",
      status: "AVAILABLE",
      locationAddress: "Shwepyitha, Yangon",
      coordinates: [16.9, 95.98],
      images: ["house13.jpg", "house14.jpg", "house15.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 0.6,
      parkingSpaces: 2,
      yearBuilt: 2013,
      petAllowed: true,
      appliances: ["Fan"],
      availableDate: "2026-05-03T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "Ooredoo",
      internetSpeed: "50 Mbps",
    },
    {
      title: "Villa in Thanlyin",
      description:
        "A modern villa located in Thanlyin offering peaceful surroundings and improving connectivity to Yangon.",
      baseRentPrice: 2000000,
      beds: 4,
      baths: 3,
      area: 3000,
      propertyType: "Villa",
      status: "AVAILABLE",
      locationAddress: "Thanlyin, Yangon",
      coordinates: [16.73, 96.25],
      images: ["villa13.jpg", "villa14.jpg", "villa15.jpg"],
      nearTransitType: "Bus Stop",
      nearTransitDist: 2.5,
      parkingSpaces: 2,
      yearBuilt: 2021,
      petAllowed: true,
      appliances: ["AC", "Oven"],
      availableDate: "2026-05-06T00:00:00.000Z",
      leaseTermMonths: 12,
      internetName: "MyTel Fiber",
      internetSpeed: "150 Mbps",
    },
  ];

  for (const property of properties) {
    await prisma.property.create({
      data: { ...property, landlordId: "1574e2ff-8cc6-4b27-8439-97e7f5e3f633" },
    });
  }
  console.log("Properties created successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
